#!/usr/bin/env bash
#this will print best school 10 times with Hi on the nineth itteration
n=1
while [ "$n" -le 10 ]
do
if [ "$n" -eq 9 ]; then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
((n++))
done
