#!/usr/bin/env bash
#this will print different text on different iterations 
n=1
while [ "$n" -le 20 ]
do
echo "$n"
case "$n" in
4)
echo "bad luck from China"
;;
esac
case "$n" in
9)
echo "bad luck from Japan"
;;
esac
case "$n" in
17)
echo "bad luck from Italy"
;;
esac
((n++))
done
