#!/usr/bin/env bash
#this will print different text on different iterations 
hour=0
while [ "$hour" -le 12 ]
do
echo "Hour: $hour"
minute=1
while [ "$minute" -le 59 ]
do
echo "$minute"
((minute++))
done
((hour++))
done
