#!/usr/bin/env bash
#this will check if the file exists and if it is a regular file 

file_name="school"
if [ -e $file_name ]; then
    echo "school file exists"
    if [ ! -s $file_name ]; then 
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f $file_name ]; then
        echo "shool is a regular file"
    fi  
else   
    echo "school does not exist"
fi
